# Generated by Django 6.1 on 2026-08-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_productgallery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.ImageField(upload_to="store/products"),
        ),
    ]
