# Generated by Django 6.1 on 2026-08-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_product_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.ImageField(blank=True, upload_to="store/products"),
        ),
    ]
