# Generated by Django 6.1 on 2026-08-28 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_product_images"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSKU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "color",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"variation_category": "color"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="color_skus",
                        to="store.variation",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skus",
                        to="store.product",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"variation_category": "size"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="size_skus",
                        to="store.variation",
                    ),
                ),
            ],
            options={
                "verbose_name": "product SKU",
                "verbose_name_plural": "product SKUs",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "color", "size"),
                        name="unique_product_color_size_sku",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.product"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "product")},
            },
        ),
    ]
