# Generated by Django 6.1 on 2026-08-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
        ("store", "0002_variation"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="varation",
            field=models.ManyToManyField(blank=True, to="store.variation"),
        ),
    ]
