# Generated by Django 6.1 on 2026-08-19 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0002_cartitem_varation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="varation",
            new_name="variation",
        ),
    ]
