# Generated by Django 6.1 on 2026-08-19 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0003_rename_varation_cartitem_variation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="variation",
            new_name="variations",
        ),
    ]
