# Generated by Django 6.1 on 2026-08-28 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0005_cartitem_user_alter_cartitem_cart"),
        ("store", "0007_product_sku_wishlist_coupons"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="sku",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.productsku",
            ),
        ),
    ]
