# Generated by Django 6.1 on 2026-08-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="pin_code",
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
