# Generated by Django 6.1 on 2026-08-28 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_orderproduct_color_remove_orderproduct_size"),
        ("store", "0007_product_sku_wishlist_coupons"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "Percent"), ("fixed", "Fixed amount")],
                        default="percent",
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.FloatField(
                        help_text="Percent (0-100) or fixed amount in USD"
                    ),
                ),
                ("min_amount", models.FloatField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("usage_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("used_count", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="discount",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="stock_restored",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="sku",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.productsku",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orders.coupon",
            ),
        ),
    ]
